### ISSUE TITLE
SORA Card Referral Program

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#1]
# User story

As a SORA Card user I want to invite people to order and use SORA Card so that I can help grow the ecosystem and get rewarded for helping grow the ecosystem.

# Requirements

1. Referral Link Integration  
- The referral link must be linked to a specific SORA Card account, which can be linked to multiple SORA and other blockchain Addresses.  
- The referral process should be seamless and invisible to the user. Users will need to follow the referral link without manually entering any referral code.

2. Reward Criteria  
Both the referee and referrer will each receive EUR 25 worth of XOR once the following conditions are met:  
- Referee successfully completes the KYC (Know Your Customer) process.  
- Referee completes a trading volume of at least EUR 1000 (XOR to EUR or EUR to XOR).  

3. Reward Distribution  
- Upon meeting the criteria, both the referee’s and the referrer’s balances will automatically receive EUR 25 worth of XOR each.  
- The distribution will occur from a crypto wallet, credited directly to both parties.
- The funds are automatically transferred from a dedicated wallet. If there are insufficient funds, the administrator is notified via Telegram for each failed payment.

4. Referral Tracking  
- Referral actions are tracked using webhooks of the Account_Transaction type.  
- These webhooks are captured by the middleware, where the data is automatically aggregated and processed once received.

5. Configurable Parameters  
- All key numeric parameters, such as the trading volume threshold (EUR 1000), are configurable. This allows flexibility in adjusting the requirements.

# Solution

TBA

# Flow

**Step 1.** Service subscribes to the historical blockchain data using Subquery instance:

TBA

# Tasks

## Backend

- [ ] TBA

## Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/34
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/12

## Mobile

- Design
  - [ ] https://github.com/sora-xor/sora-card/issues/35
- Development
  - [ ] https://github.com/sora-xor/sora-card-ios/issues/19
  - [ ] https://github.com/sora-xor/sora-card-android/issues/3

Aha! Link: https://soramitsucoltd.aha.io/features/SC-15

**Comment by Tieumsan** [comment]
Comment added by Soramitsu Labs in Aha! - [View](https://soramitsucoltd.aha.io/comments/7268638954120273795)

Need gatehub doc
