### ISSUE TITLE
Display SORA Card Transactions

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#10]
As a <ins>SORA Card user</ins> I want to <ins>see the transactions I made with the SORA Card</ins> so that <ins>I can follow up on my expenses</ins>.

**Documentation** : [https://iban-test.paywings.io/whitelabel/ListTransactions](https://iban-test.paywings.io/whitelabel/ListTransactions)

# Tasks

## Web

- Design
  - [ ] https://github.com/sora-xor/sora-card/issues/22
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/6

## Mobile

- Design
  - [ ] https://github.com/sora-xor/sora-card/issues/23
- Development
  - [ ] https://github.com/sora-xor/sora-card-ios/issues/18
  - [ ] https://github.com/sora-xor/sora-card-android/issues/4

Aha! Link: https://soramitsucoltd.aha.io/features/SC-13
