### ISSUE TITLE
Enforce Application Version Update

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#109]
# Problem

Currently, our applications do not check for the latest version, which can lead to compatibility issues with the middleware. It is essential to ensure that applications always fetch the latest version from the middleware to maintain compatibility and provide a seamless user experience

# Solution

To address this issue, we need to enforce the SORA Card version update process. 

# Sub-tasks & Requirements

This involves making changes to both the backend and client applications to ensure they always fetch and use the latest version from the middleware

## Backend

- Requirements
  - The most recent version will be manually configured and updated within the CI/CD, indicating that there is no need for a POST method
  - The resulting value should have the following object:
```
{
  "ios_client_version": "2.2.0",
  "android_client_version": "2.2.0",
  "api_version":"0.9.4",
  "build_timestamp":"2023-10-04T08:33:16.228670675Z",
  "git_pretty":"fe21ef5"
}
```
- Sub-tasks
  - [x] https://github.com/soramitsu/sora-card-backend/issues/347

## Client Applications

- Requirements
  - The application should retrieve the version from `/version` endpoint and compare it to the locally stored version

### Web

- Requirements
    - No changes are required

### Mobile

- Requirements
  - The application should only deal with the object that is specific to its platform (e.g., `ios_client_version` for iOS and `android_client_version` for Android).
  - Handling the fetched latest version
    - If the fetched version has a different version, it should block SORA card functionality entirely and prompt the user to update the application
    - If the user is already using the latest version of the application, no action is required
- Sub-tasks
  - Design
    - [x] https://github.com/sora-xor/sora-card/issues/110
  - Development
    - [x] https://github.com/sora-xor/sora-card-ios/issues/93
    - [x] https://github.com/sora-xor/sora-card-android/issues/138

**Comment by Alexey-N-Chernyshov** [comment]
Now we have /version endpoint which returns mw API version:
```
{
  "semver":"0.9.4",
  "build_timestamp":"2023-10-04T08:33:16.228670675Z",
  "git_pretty":"fe21ef5"
}
```
I suggest to add all client supported versions for mw, respectively: web, ios, android, so response will be:
```
{
  "web_client_version": "1.2.3",
  "android_client_version": "3.4.5",
  "ios_client_version": "4.5.6",
  "api_version":"0.9.4",
  "build_timestamp":"2023-10-04T08:33:16.228670675Z",
  "git_pretty":"fe21ef5"
}
```
The client will check corresponding version and decide should it proceed or force update.
Also we should decide do the client must update on patch change. Patch change usually means bug fixing. Another possible solution is to update client minor version on bug fixing. We should come up to some agreement on this example.

**Comment by bgodlin** [comment]
> The client will check corresponding version and decide should it proceed or force update. Also we should decide do the client must update on patch change. Patch change usually means bug fixing. Another possible solution is to update client minor version on bug fixing. We should come up to some agreement on this example.

Should the application solely verify its object or should it also manage the `api_version` object in some way?

**Comment by Alexey-N-Chernyshov** [comment]
The client should check `xxx_client_version` only. There is no need to check both api and client version since the client will support the most recent mw api.

**Comment by Alexey-N-Chernyshov** [comment]
Final version, `ios_client_version` is set by env:
```
{
  "ios_client_version": "4.5.6",
  "api_version":"0.9.4",
  "build_timestamp":"2023-10-04T08:33:16.228670675Z",
  "git_pretty":"fe21ef5"
}
```
