### ISSUE TITLE
Gatehub Integration

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#11]
As a SORA Card user I want to buy fiat currency with my crypto within the wallet so that I can trade in the Traditional Finance economy seamlessly.

# Tasks

## Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/20
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/5

## Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/21
- Development
  - [x] https://github.com/sora-xor/sora-card-ios/issues/20
  - [ ] https://github.com/sora-xor/sora-card-android/issues/6

Aha! Link: https://soramitsucoltd.aha.io/features/SC-16

**Comment by Ophelia36** [comment]
Hi @Tieumsan  I suggest you contact wallet UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by Tieumsan** [comment]
@bgodlin documentation received from partners. They mentioned that it is an old version that will be slightly updated. No major changes excepted.

https://cryptogatewaytest.paywings.io/whitelabel/docs

**Comment by bgodlin** [comment]
@Tieumsan I'll test it out, thank you!
