### ISSUE TITLE
Update logic for KYC SDK language selection

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#117]
# Problem Statement
The current implementation to choose the language to use in the KYC SDK is always english. The KYC SDK has several languages supported. 
If the active language of the app is in the list of languages supported in the KYC SDK, then the KYC should use the active language. Otherwise, the default language should be used (English).

# Context

The KYC SDK is used within various applications.
The KYC SDK supports multiple languages.
The current behavior always uses English as the language.

# Requirements

- The KYC SDK should detect the active language of the host application.
- Check if the active language is supported within the KYC SDK's list of languages.
- If the active language is supported, set it as the language for the KYC process.
- If the active language is not supported, fall back to the default language (English).

# Sub-tasks

- [x] https://github.com/sora-xor/sora-card-ios/issues/114
- [x] https://github.com/sora-xor/sora-card-android/issues/163
- [x] https://github.com/sora-xor/sora-card-web/issues/39

**Comment by 2bogd** [comment]
@bgodlin Have we decided to hardcode the KYC SDK's list of  supported languages in clients and maintain it?
