### ISSUE TITLE
Temporary Removal of X1

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#119]
# Issue

Presently, users are experiencing inconsistencies between the amounts paid in EUR and the amounts received in XOR, related to ongoing issues on the exchange side.

# Proposed Resolution

Temporarily disable the functionality until the issue is resolved on the backend.

# Sub-Tasks

- [x] https://github.com/sora-xor/sora-card-ios/issues/112
- [x] https://github.com/sora-xor/sora-card-web/issues/38
- [x] https://github.com/sora-xor/sora-card-android/issues/161
