### ISSUE TITLE
Pay with SORA Card (GooglePay / ApplePay)

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#12]
As a <ins>SORA Card owner</ins> I want to <ins>seamlessly pay in fiat with my crypto through my mobile phone with GooglePay</ins> so that <ins>I can easily close the gap between the TradFi and DeFi worlds</ins>.

# Tasks

## Mobile

- Design
  - [ ] https://github.com/sora-xor/sora-card/issues/19
- Development
  - [ ] https://github.com/sora-xor/sora-card-android/issues/7
  - [ ] https://github.com/sora-xor/sora-card-ios/issues/22

Aha! Link: https://soramitsucoltd.aha.io/features/SC-17
