### ISSUE TITLE
Show error message on the X1 screen when user's country is blocked

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#13]
# Problem statement
When a user opens the X1 widget with an IP that is from a country from the list of blacklisted countries, the X1 widget shows a white screen.

# Definition of Done
The user sees an explicit error message and some recommendations.

https://user-images.githubusercontent.com/44833388/232830780-1bf5c3e7-c41b-485d-8bfb-b8206b792aa2.mp4

# Tasks

## Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/17
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/4

## Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/18
- Development
  - [x] https://github.com/sora-xor/sora-card-android/issues/16
  - [x] https://github.com/sora-xor/sora-card-ios/issues/11

Aha! Link: https://soramitsucoltd.aha.io/features/SC-18
