### ISSUE TITLE
See X1 transaction status

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#14]
As a <ins>user that is trying to buy XOR with fiat</ins> I want to <ins>see the status of my transaction with the exchange (X1)</ins> so that <ins>I can see if my transaction is still being processed, has been successful or rejected</ins>.

**Documentation**: https://x1ex.com/docs/API.pdf

# Tasks

## Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/16
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/3

## Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/15
- Development
  - [x] https://github.com/sora-xor/sora-card-android/issues/22
  - [x] https://github.com/sora-xor/sora-card-ios/issues/25

Aha! Link: https://soramitsucoltd.aha.io/features/SC-18

**Comment by bgodlin** [comment]
Won't do
