### ISSUE TITLE
Log out of SORA Card Account

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#3]
# User story
As a <ins>SORA Card user</ins> I want to <ins>log out of my current SORA Card account</ins> so that <ins>I can remove data from my fiat account on the crypto wallet if I fancy</ins>.

# Preconditions
- User has successfully completed the authorisation (does not matter what KYC status is one currently having)

# Flow

1. User clicks on the Logout button
2. `user_id` of the user is deleted, the session with SORAcard is closed

# Postcondition
The user has been logged out. One can go through authorization again (either for another user, or for the one for whom one just logged out).

# Tasks

### Web

- Implementation
  - [x] https://github.com/sora-xor/sora-card-web/issues/2

### Mobile

- Design
  - [x] https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872-10297&mode=design&t=T0MFEg0U4SNF13CE-0
- Implementation
  - [x] https://github.com/sora-xor/sora-card-android/issues/2
  - [x] https://github.com/sora-xor/sora-card-ios/issues/10

## Documentation

- [x] https://github.com/sora-xor/sora-docs/issues/34

Aha! Link: https://soramitsucoltd.aha.io/features/SC-8
