### ISSUE TITLE
Reformulate sentence in SORA Card registration entry point

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#45]
In the [current entry point to register for the SORA Card](https://www.figma.com/file/5kaHWqH73Ekez7RVOpH36g/%E2%9C%85-SORA-Wallet-(on-Prod)?type=design&node-id=11712-28906&t=dKhzvy3x4LHf3ZTE-0), the phrase says: "Get a Euro IBAN account and Mastercard Debit Card connected to your SORA Wallet". This is inaccurate because we specifically don't want to connect the SORA IBAN to the SORA account.

## Tasks
Reformulate the phrase to: "Get a Euro IBAN account and Mastercard Debit Card accessible within your SORA Wallet"

#### Design

- [x] sora-xor/sora-card-web#14

#### Development

- [x] sora-xor/sora-card-web#15

#### Design
- [x] #47
#### Development
- [x] sora-xor/sora-card-android#35
- [x] sora-xor/sora-card-ios#36
