### ISSUE TITLE
Add complementary message on Verify email

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#48]
We need to guide users throughout the KYC process and alleviate any source of stress/uncertainty for users.

**Current message**: "Follow the magic link that has been sent to [email]"
**Target message**: "Follow the magic link that has been sent to [email] \n The email might take several minutes to arrive. Please verify your spam folder if you haven't received the email after 5 minutes."

- [x] sora-xor/sora-card-android#52
- [x] sora-xor/sora-card-ios#45
- [x] sora-xor/sora-card-web#16

**Comment by Tieumsan** [comment]
Updated in Lokalise. 

@spitsynval please update in the design in Figma: https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1501-11504&mode=design&t=iG8dwpl7OvzNfbKv-0
