### ISSUE TITLE
Display SORA Card Entry Point on Main Screen

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#5]
As a <ins>SORA Card user</ins> I want to <ins>have an entry point to the SORA Card hub on the SORA Wallet main screen</ins> so that <ins>I can easily access the hub</ins>.

# Tasks

## Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/33
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/11

## Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/32
  **Link**: https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872-10422&mode=design&t=T0MFEg0U4SNF13CE-0
- Development
  - [x] https://github.com/sora-xor/sora-card-ios/issues/12
  - [x] https://github.com/sora-xor/sora-card-android/issues/11

Aha! Link: https://soramitsucoltd.aha.io/features/SC-7
