### ISSUE TITLE
Display SORA Account IBAN

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#52]
# User story

As a <ins>SORA Card owner</ins> I want to <ins>see my account IBAN</ins> so that <ins>I can share it to receive money on it</ins>.

# AHA link

Aha! Link: https://soramitsucoltd.aha.io/features/SC-41

# Sub-tasks

The implementation will encompass obtaining the IBAN via the middleware, similar to how it's carried out for other integration methods within the client applications. This necessitates the addition of logic to both the backend and client application. Further details on each component can be found in the subsequent sub-chapters

## Backend

- [x] https://github.com/soramitsu/sora-card-backend/issues/246

## Client applications

- Precondition
  - The user has a valid account and is logged in
- Requirements 
  - The application automatically fetches the required data from the backend each time the screen is accessed (see request model in https://github.com/soramitsu/sora-card-backend/issues/246). The retrieved data is then displayed on the screen
  - The user intends to update the list of IBANs
    - On web platforms, the user can initiate an update by performing a page reload
    - On mobile applications, the user can initiate an update by utilizing the drag-and-drop functionality
  - The application stores the fetched data in a cache to ensure accessibility even when offline
  - The application should provide the user with the timestamp of the last data retrieval. This timestamp allows users to determine the freshness of the displayed data
  - The IBAN field should be copiable
  - After getting the KYC verification successfull, it might take 5-10 minutes to create the IBAN. Therefore, there should be good UX indicating the user that one's IBAN is being prepared. TODO append with the integration methods
- Postcondition
  - The user is able to access up-to-date information and conveniently update the list of IBANs using appropriate user experience methods. The application ensures data accessibility even in offline mode through caching mechanisms

### Web

- [x] https://github.com/sora-xor/sora-card-web/issues/18 

### Mobile

- [x] https://github.com/sora-xor/sora-card-ios/issues/49
- [x] https://github.com/sora-xor/sora-card-android/issues/55
