### ISSUE TITLE
[Tech]: Remove option to change receiving address in X1 widget

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#54]
### Problem statement
Currently users can choose whether to send the XOR they buy through the X1 widget to their SOR address (external) or to the X1 address. To avoid any confusion, we should remove the option to send funds to the X1 address and only allow to send funds to the SORA address.

### Definition of Done
 Option to change receiving address disabled

### Requirements

As the widget is being initialized, the inclusion of the following two parameters is necessary:

DEV/TEST env.
`data-to-blockchain="TXOR"` and `data-disable-to-blockchain="true"`

PROD env.
`data-to-blockchain="XOR"` and `data-disable-to-blockchain="true"`

### Sub-tasks

- [x] https://github.com/sora-xor/sora-card-web/issues/20
- [x] https://github.com/sora-xor/sora-card-android/issues/90
- [x] https://github.com/sora-xor/sora-card-ios/issues/60
