### ISSUE TITLE
[Tech]: Phone number validation

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#57]
### Problem Statement
We currently don't have a validation system to ensure the users can only submit valid numbers to receive the OTP and proceed with signing in. 

### Definition of Done

- [ ] Regular expression `^[+][0-9]{8,16}$` for the phone number input to comply with the format required by our partner's SDK (international format)
- [ ] Improvement on the UI to hint on the format required

### Sub-tasks

Design: 

- [x] https://github.com/sora-xor/sora-card/issues/68

Development:

- [x] sora-xor/sora-card-ios#64
- [x] sora-xor/sora-card-android#92
- [x] https://github.com/sora-xor/sora-card-web/issues/24

**Comment by spitsynval** [comment]
Mobile: https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1501%3A11483&mode=design&t=HIVFHK6Qm9ubU6C0-1

Web: https://www.figma.com/file/aDkwf6C8zmyJjudJOuuhrH/Polkaswap-v1.x.x-(Current)?type=design&node-id=16988%3A1186&mode=design&t=iEGaH6n6vBn76r0i-1
