### ISSUE TITLE
Add disclaimer on documents accepted for proof-of-address

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#63]
### Problem Statement
Users experienced unclear rejection because their proof of address were not accepted by our partner.
Sumsub is currently rejecting neobank bank statements: Revolut, N26, ...
It should work if you apply with a regular commercial bank statement.

**Documents accepted by SumSub**: https://help.sumsub.com/products/supported-poa-documents#which-documents-count-as-proof-of-address

## Definition of Done
- [ ] Add the following disclaimer in the page with the steps summary and documents required, at the end of "3 - Submit a Photo of proof of address": "_Statements from neobanks like Revolut and N26 are currently not seen as valid proof of address_"

### Web
**Design**: https://github.com/sora-xor/sora-card-web/issues/22#issuecomment-1702626915

- [x] sora-xor/sora-card-web#22

### Mobile
**Design**: https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1501-11445&mode=design&t=1ZjQplDoXUsb1hzG-0

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] sora-xor/sora-card-android#94

- [x] sora-xor/sora-card-ios#66
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by BenoXYZ** [comment]
Add the following disclaimer in the page with the steps summary and documents required, at the end of "3 - Submit a Photo of proof of address":
"Statements from neobanks like Revolut and N26 are currently not seen as valid proof of address"

**Comment by spitsynval** [comment]
Updated design for SORA Mobile: https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1501%3A11302&mode=design&t=E3L65qbCp5p3HovS-1

**Comment by 2bogd** [comment]
Blocked by Localize (no translation).
@Tieumsan this key https://app.lokalise.com/project/828171766350fbd5dd3c48.67230943/?view=multi&search=get.prepared.proof.address.description need to be updated on all languages before release 3.3.0.
