### ISSUE TITLE
Pay for KYC with card

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#7]
As a <ins>user</ins> I want to <ins>pay for the SORA Card with fiat currency (euros)</ins> so that <ins>I am not obliged to hold crypto to get SORA Card</ins>.

Requirements:

- Integration with Unlimint

**Documentation** : [https://docs.paywings.io/PaymentGateway.html](https://docs.paywings.io/PaymentGateway.html)_We should use hosted fields or hosted forms._

# Tasks

## Web

- Design
  - [ ] https://github.com/sora-xor/sora-card/issues/28
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/9

## Mobile

- Design
  - [ ] https://github.com/sora-xor/sora-card/issues/29
- Development
  - [ ] https://github.com/sora-xor/sora-card-ios/issues/21
  - [ ] https://github.com/sora-xor/sora-card-android/issues/5

Aha! Link: https://soramitsucoltd.aha.io/features/SC-14
