### ISSUE TITLE
[Tech] Update the link to the Telegram support

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#71]
### Problem Statement
We now have a support Telegram chat dedicated to SORA Card. We need to update it in the apps.

### Definition of Done
**New link**: https://t.me/soracardofficial

#### Web

- [x] sora-xor/sora-card-web#26

#### Mobile

- [x] sora-xor/sora-card-android#98
- [x] sora-xor/sora-card-ios#71
