### ISSUE TITLE
Display SORA Card IBAN Balance in the SORA Card Hub

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#8]
As a <ins>SORA Card user</ins> I want to <ins>have an overview of my SORA Card account within the crypto wallet</ins> so that <ins>I can easily access my fiat wallet from my crypto wallet</ins>.

Documentation: [https://iban-test.soracard.com/whitelabel/ListIbans](https://iban-test.soracard.com/whitelabel/ListIbans)

# Requirements

## Backend

Implemented as part of https://github.com/soramitsu/sora-card-backend/issues/246

## Client applications

- `/ListIbans` (implemented as part of https://github.com/sora-xor/sora-card/issues/52) should be called to receive the relevant balance, no additionals calls will have to be performed. The AvailableBalance field should be utilized and subsequently displayed on every occasion.
- The application should automatically fetch the required data from the backend each time the screen is accessed (see request model in https://github.com/soramitsu/sora-card-backend/issues/246).
- 0 balance to be displayed as `0`

# Tasks

## Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/27
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/8

## Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/26
- Development
  - [x] https://github.com/sora-xor/sora-card-ios/issues/16
  - [x] https://github.com/sora-xor/sora-card-android/issues/8

Aha! Link: https://soramitsucoltd.aha.io/features/SC-10

**Comment by 2bogd** [comment]
In Documentation:

- Minor unit is the smallest denomination of a currency unit, in case of euros, 1 minor unit is cent
- All balances are in euros.
- The balance that is relevant to the user is available balance

**Comment by 2bogd** [comment]
Do we have loading / error states design ?

**Comment by bgodlin** [comment]
> Do we have loading / error states design ?

To be implemented in the next release
