### ISSUE TITLE
Show SORA Card Details

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#9]
As a <ins>SORA Card user</ins> I want to <ins>see my cards details</ins> so that <ins>I can use or copy them at my convenience</ins>.

Documentation: [https://iban-test.soracard.com/whitelabel/ListCards](https://iban-test.soracard.com/whitelabel/ListCards)

Aha! Link: https://soramitsucoltd.aha.io/features/SC-11

# Tasks

## Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/25
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/7

## Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/24
- Development
  - [x] https://github.com/sora-xor/sora-card-android/issues/9
  - [x] https://github.com/sora-xor/sora-card-ios/issues/17

**Comment by bgodlin** [comment]
Yet no functionality done by partners

**Comment by bgodlin** [comment]
Currently, it is not feasible due to the following reasons:

1. The API does not provide CVV.
2. The card number is returned with certain digits hidden.
