### ISSUE TITLE
Make application and retry fees dynamically fetched

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#90]
## Problem Statement
The fee to pay for the KYC application to get the card might change over the product lifecycle. If we have a value hard-coded on all the client applications, this might bring inconsistencies and misunderstanding the next time we update the application fee (€). 

## Solution
Rather than relying on hard-coded values, it would make sense to enable to fetch the application fee from the backend.

### Backend

- [x] [Store the application fee in the backend](https://github.com/soramitsu/sora-card-backend/pull/290)
- [x] [Endpoint to fetch the application fee](https://github.com/soramitsu/sora-card-backend/issues/289)
- [x] https://github.com/soramitsu/sora-card-backend/issues/323

### Client Applications
See data structures in backend task and documentation.

- [x] sora-xor/sora-card-android#116
- [x] sora-xor/sora-card-ios#77
- [x] sora-xor/sora-card-web#29

**Comment by Alexey-N-Chernyshov** [comment]
Added endpoint `/fees` that returns:
`{"application_fee":"29","retry_fee":"3.80"}`
