### ISSUE TITLE
Upgrading to a more recent iteration of the KYC SDK

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#96]
# Sub-tasks
- [x] https://github.com/sora-xor/sora-card-android/issues/127
- [x] https://github.com/sora-xor/sora-card-ios/issues/82
- [x] https://github.com/sora-xor/sora-card-web/issues/30
