### ISSUE TITLE
 Improving UI for the transitional phase between Verified KYC and Provisioned IBAN

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#99]
# Problem

At present, there is no specific handling for the phase in which KYC has been successfully reviewed, but the IBAN has not yet been provided (this phase also involves the AML compliance check).

# Solution

Hence, it is necessary to offer a user-friendly hint during this phase to inform users that they are currently undergoing the verification process.

# Sub-tasks

## Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/104
- Development
  - [ ]  https://github.com/sora-xor/sora-card-web/issues/33

## Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/103
- Development 
  - [x] https://github.com/sora-xor/sora-card-android/issues/131
  - [x] https://github.com/sora-xor/sora-card-ios/issues/86

**Comment by bgodlin** [comment]
TBD as part of https://github.com/sora-xor/sora-card/issues/94

**Comment by bgodlin** [comment]
> TBD as part of #94

Following the release, this matter has been attended to and an improvement has been requested. Therefore, this issue will be reopened.

**Comment by bgodlin** [comment]
> IBAN issuance is dependent on KYC + AML approval so I would keep the "pending" until approved for KYC+AML and then go straight to the SORA Card hub where IBAN should be shown.
If pending for a long time, users should email to techsupport@soracard.com for whatever rejection reason.
The "congratulations" screen can be taken out, unless we can have it pop-up before opening SORA Card hub for the first time after passing screening

**Comment by spitsynval** [comment]
@BenoXYZ @Tieumsan @bgodlin 

https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=6016%3A3508&mode=design&t=5ftTfKhtMM5BQBMp-1

I crafted some drafted text, would be great if you could edit it to be shorter and more to the point :)

**Comment by ab10001** [comment]
Mobile:

https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=6016%3A3508&mode=design&t=5ftTfKhtMM5BQBMp-1


Web:
https://www.figma.com/file/aDkwf6C8zmyJjudJOuuhrH/Polkaswap-v1.x.x-(Current)?type=design&node-id=17942%3A46103&mode=design&t=Yz2zMS5ynWmj5xIs-1
